### ISSUE TITLE
Sphinx links to typedoc are broken

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3311]
E.g. in https://microsoft.github.io/CCF/main/build_apps/js_app_bundle.html:

https://microsoft.github.io/CCF/main/js/ccf-app/interfaces/global.ccf.html

But also on https://microsoft.github.io/CCF/main/build_apps/js_app_ts.html

This seems to be an upper/lower-case issue where the real file names are mixed upper/lower case and the links are all-lowercase.

**Comment by letmaik** [comment]
https://github.com/microsoft/CCF/pull/3189 updated typedoc from ^0.20.34 to ^0.22.7. Previously, typedoc generated lowercase filenames, now they have the actual casing. The change was made in https://github.com/TypeStrong/typedoc/releases/tag/v0.21.3: "Files are now created with the same case as your exported member names. This could cause broken links for external links to doc pages."

Removing our own `.lower()` should fix the issue but it would probably then break the doc links for previous CCF versions since it all runs from the same `conf.py`. Making it conditional based on the CCF version should work? I'm not sure if that's easily possible.

**Comment by achamayou** [comment]
If typedoc remains constant, then we should be fine, if it's installed for each version, we can detect the version of typedoc and switch on that?

**Comment by achamayou** [comment]
Assuming the new typedoc works with the old code, we can use the usual sed hack to force upgrade them all.

**Comment by achamayou** [comment]
@letmaik that didn't fix it, the issue persists (eg. https://microsoft.github.io/CCF/main/build_apps/js_app_ts.html)

**Comment by achamayou** [comment]
My bad, it's fine, the job wasn't done running.
